### ISSUE TITLE
151	3.1.  Type 1 - Destination IPv6 Prefix

### ISSUE THREAD

**Issue by stoffi92** [stoffi92/draft-ietf-idr-flow-spec-v6#29]
151	3.1.  Type 1 - Destination IPv6 Prefix
...
156	   Defines the destination prefix to match.  The offset has been defined
157	   to allow for flexible matching on part of the IPv6 address where it
158	   is required to skip (don't care) of N first bits of the address.
159	   This can be especially useful where part of the IPv6 address consists
160	   of an embedded IPv4 address and matching needs to happen only on the
161	   embedded IPv4 address.  The encoded prefix contains enough octets for
162	   the bits used in matching (length minus offset bits).

[nit] s/on part of/on the part of

[major] Maybe it's just me, but I find the description confusing.
After reading it several times, and looking at the examples, I think
that the length indicates the "length, in bits, of the address prefix"
(quoting rfc4760).  But the length of the prefix field (which is
different than the address prefix) is the "length minus offset bits"
(not related to rfc4760).

[I am mentioning rfc4760 because in rfc5575bis the reference to
rfc4271 was used (and very convenient).]

Please explicitly indicate what each field means.  I'm thinking of
something like this:

   the length field indicates the length, in bits of the address prefix

   the offset field indicates the N first bits that are ignored/skipped/don't
   carefully

   the prefix field includes the address prefix, it's length can be
derived from...

[Using paragraphs instead of bullets is ok of course, to keep with the
style of the document.]

[major] Looking at the examples, it is not obvious to me how the
encoding is done.  Both examples use 40 bits to encode the prefix
field...but the 'length-offset' operation is 39 in the second example.
The use of trailing bits is not mentioned -- see the definition in
rfc4760.

**Comment by stoffi92** [comment]
Is this better (adding a list containing a description of each field ... renaming the misleading "prefix" field (it is no prefix) to "pattern" + "padding"?

```
3.1.  Type 1 - Destination IPv6 Prefix

   Encoding: <type (1 octet), length (1 octet), offset (1 octet),
   pattern (variable), padding(variable) >

   Defines the destination prefix to match.  The offset has been defined
   to allow for flexible matching on part of the IPv6 address where it
   is required to skip (don't care) of N first bits of the address.
   This can be especially useful where part of the IPv6 address consists
   of an embedded IPv4 address and matching needs to happen only on the
   embedded IPv4 address.  The encoded pattern contains enough octets
   for the bits used in matching (length minus offset bits).

   lengh -  The length field indicates the N-th leftmost bit in the
      address where bitwise pattern matching stops.

   offset -  The offset field indicates the number of leftmost address
      bits to skip before bitwise pattern matching starts.

   pattern -  Contains the matching pattern.  The length of the pattern
      is defined by the number of bits needed for pattern matching
      (length minus offset).

   padding -  The minimum number of bits required to pad the component
      to a octet boundary.  Padding bits MUST be 0 on encoding and MUST
      be ignored on decoding.
```

Please suggest a alternative that we can go with (maybe can come up with a better English version ;-) ).

**Comment by raszuk** [comment]
Looks good.

**Comment by suehares** [comment]
I like the list describing the individual fields.   
What do you think Robert?  I could not tell what "looks good" implied.

**Comment by stoffi92** [comment]
I think that with "looks good" Robert refers to the text that I suggested... -> patching + close

**Comment by stoffi92** [comment]
//doc 
Added explicit individual description of the fields. Also edited the list so that it is clear that we have optional padding and a pattern that gets matched.
