### ISSUE TITLE
352	5.  Validation Procedure

### ISSUE THREAD

**Issue by stoffi92** [stoffi92/draft-ietf-idr-flow-spec-v6#42]
352	5.  Validation Procedure

354	   The validation procedure is the same as specified in
355	   [I-D.ietf-idr-rfc5575bis] Section 6 with the exception that item a)
356	   of the validation procedure should now read as follows:

358	      a) A destination prefix component with offset=0 is embedded in the
359	      Flow Specification

[major] Why is the FS considered valid only if offset=0 is used?
Given that each component can exist only once, then there seems to be
no point in using the offset in the destination component.  Also, the
examples above are then unfeasible because neither uses offset=0.  Am
I missing something?

**Comment by stoffi92** [comment]
//doc
The problem with offset != 0 that it generates non-contiguous prefix matches:
For example a matching pattern of ::1234:5678:9A00:0/64-104:

```
0000:0000:0000:0000:1234:5678:9A00:0000 - 0000:0000:0000:0000:1234:5678:9A03:FFFF matches
0000:0000:0000:0000:1234:5678:9A04:0000 - 0000:0000:0000:0000:1234:5678:99FF:FFFF does not
... (many in between)
2001:0DB8:0000:0000:1234:5678:9A00:0000 - 2001:0DB8:0000:0000:1234:5678:9A03:FFFF matches
2001:0DB8:0000:0000:1234:5678:9A04:0000 - 2001:0DB8:0000:0001:1234:5678:99FF:FFFF does not
2001:0DB8:0000:0001:1234:5678:9A00:0000 - 2001:0DB8:0000:0001:1234:5678:9A03:FFFF matches
and so on...
```

Offset != 0 is only useful in a trusted environment when the validation has been relaxed.

**Comment by stoffi92** [comment]
@suehares @raszuk - is there anything more needed?

**Comment by raszuk** [comment]
I think this is fine. We could (if we really wanted) validate partial address too (skipping first N bits) just to detect the cases when peer never advertises with any prefix this part of route (subject to validation). But I am not sure we want to spend much time on this here.

**Comment by suehares** [comment]
I think this is fine.  We need to simply indicate to Alvaro that there is an encoding issues if it is not set to zero. 
We'll get a feedback that he wants more text.  

You could respond to Alvaro with this single response before you send all the responses.   As we discuss the redirect issue, it may be helpful to work this issues out with Alvaro in parallel.

**Comment by stoffi92** [comment]
@suehares, I can send a copy of my comment to Alvaro/IDR to point out that prefix!=0 is only useful when validation is relaxed.

**Comment by raszuk** [comment]
Sorry what prefix != 0 ? You mean offset ? 

Even so that would be too general. When offset x mask is applied to src address as example validation can stay intact. So we need to be very specific that this is only about offset applied to dst address match where validation as defined today may be tricky.

**Comment by stoffi92** [comment]
> Sorry what prefix != 0 ? You mean offset ?

Yes offset. 

> Even so that would be too general. When offset x mask is applied to src address as example validation can stay intact. So we need to be very specific that this is only about offset applied to dst address match where validation as defined today may be tricky.

Validation in general is only about destination see Section 5 of the draft:

```
      a) A **destination** prefix component with offset=0 is embedded in the
      Flow Specification
```

This is the only modification to the valdiation procedure from rfc5575bis Section 6.
