### ISSUE TITLE
369	6.1.  Redirect IPv6 (rt-redirect-ipv6) Type/Sub-Type 0x80/TBD

### ISSUE THREAD

**Issue by stoffi92** [stoffi92/draft-ietf-idr-flow-spec-v6#44]
369	6.1.  Redirect IPv6 (rt-redirect-ipv6) Type/Sub-Type 0x80/TBD
...
383	   Interferes with: All BGP Flow Specification redirect Traffic
384	   Filtering Actions (with itself and those specified in
385	   [I-D.ietf-idr-rfc5575bis] Section 7.4).

[major] Ok, so this community conflicts with other redirect Traffic
Filtering Actions, including itself (?)...but the actions in
rfc5575bis/§7.4 don't conflict with anything, apparently including
themselves.  Hmmm..   Maybe we had the discussion before (I don't
remember) about conflicting with themselves -- the text in rfc5575bis
may be saying the same thing as the text here, but with different
words.

IOW, is 'doesn't conflict with anything *else*' the same as 'only
conflicts with itself'?

Let's please use consistent language.

Suggestion (assuming I'm understanding)>
   Interferes with: All BGP Flow Specification redirect Traffic Filtering
   Actions (specified in [I-D.ietf-idr-rfc5575bis] Section 7.4).

**Comment by stoffi92** [comment]
//doc
Actually this is fine. Those (actually it is only one) from rfc5575bis only interfere with themselves (since there is only one redirect community specified in rfc5575bis). Now because fs-v6 adds another redirect community this interferes with the other specified communities in rfc5575bis and also with itself.

**Comment by raszuk** [comment]
I sdo not see any conflict. I am of the opinion that operator may wish to redirect to multiple VRFs (adds multiple RTs) and what happens on the box is a local matter.

**Comment by suehares** [comment]
Robert and Christoph:   
You have chosen the two options that started me down the path of reworking flow-specification. 
We need to choose which way we will define the flow-specification redirect for v6. 

1) I agree with Christoph that the fs-v6 does interfere the way it is written now.   
2) Robert is correct that some people may wish to redirect multiple VRFs for v6. 

Robert can you propose text that provides a clear definition for multiple VRFs.   
How do operators or implementers know whether the redirect interferes or does not interfere? 
Stating it is a local affair is not really helpful in a specification for interoperability. 
You can state that it interferes unless operators set a local policy. 

Any help

**Comment by stoffi92** [comment]
@suehares @raszuk 
We have this in the ipv4 FS. This also applies to IPv6 FS. Do we need to add anything explicitly to IPv6 FS?

```
7.7.  Considerations on Traffic Filtering Action Interference

   Since Traffic Filtering Actions are represented as BGP extended
   community values, Traffic Filtering Actions may interfere with each
   other (e.g. there may be more than one conflicting traffic-rate-bytes
   Traffic Filtering Action associated with a single Flow
   Specification).  Traffic Filtering Action interference has no impact
   on BGP propagation of Flow Specifications (all communities are
   propagated according to policies).

   If a Flow Specification associated with interfering Traffic Filtering
   Actions is selected for packet forwarding, it is an implementation
   decision which of the interfering Traffic Filtering Actions are
   selected.  Implementors of this specification SHOULD document the
   behaviour of their implementation in such cases.

   Operators are encouraged to make use of the BGP policy framework
   supported by their implementation in order to achieve a predictable
   behaviour.  See also Section 12.

```
