### ISSUE TITLE
401	           +-------+-------------------------+-----------------+

### ISSUE THREAD

**Issue by stoffi92** [stoffi92/draft-ietf-idr-flow-spec-v6#48]
401	           +-------+-------------------------+-----------------+
402	           | Value | Name                    | Reference       |
403	           +-------+-------------------------+-----------------+
404	           | 1     | Destination IPv6 Prefix | [this document] |
405	           | 2     | Source IPv6 Prefix      | [this document] |
406	           | 3     | Next Header             | [this document] |
407	           | 4     | Port                    | [this document] |
408	           | 5     | Destination port        | [this document] |
409	           | 6     | Source port             | [this document] |
410	           | 7     | ICMPv6 type             | [this document] |
411	           | 8     | ICMPv6 code             | [this document] |
412	           | 9     | TCP flags               | [this document] |
413	           | 10    | Packet length           | [this document] |
414	           | 11    | DSCP                    | [this document] |
415	           | 12    | Fragment                | [this document] |
416	           | 13    | Flow Label              | [this document] |
417	           +-------+-------------------------+-----------------+

[major] The definition of some of these values is not done in "this
document", but in rfc5575bis.  In those cases, please list both as a
reference.

[major] Even if the probability is low...  If new components are
added, if they apply to both IPv4/IPv6, how will the registries be
kept in sync?  Should the Experts assign/request that an IPv4-related
request be extended to also cover IPv6 (or viceversa)?  Should the
Experts reserve the corresponding code points in the other registry?
Will we reply on the Experts to keep both registries the same?

Here's an idea:  Currently all the components either are exactly the
same, or share a name (modulo using ICMPv6 instead of ICMP, for
example).  Can we design a table that incorporates common Type/Name,
and separate columns for IPv4 and IPv6 with the proper references?

I'm thinking of something like this:

  +------+--------------------+------+------+----------------------------+
  | Type | Name               | IPv4 | IPv6 |References                  |
  +------+--------------------+------+------+----------------------------+
  | 1    | Reserved           | Y    | Y    | [rfc5575bis]               |
  +------+--------------------+------+------+----------------------------+
  | 2    | Destination Prefix | Y    |      | [rfc5575bis]               |
  |      |                    |      | Y    | [ietf-idr-flow-spec-v6]    |
  +------+--------------------+------+------+----------------------------+

...or we could put all the information for "2" in the same line with
both references.

This way we end up with one registry and no additional coordination.
Note that we can have the same Experts for both registries...but this
way they'll never fall out of sync.

If we go this way, or something similar, then we'll need to formally
Update rfc5575bis to change the registry format (no change needed in
that other document).

**Comment by stoffi92** [comment]
@raszuk @suehares 

I am not sure if such a tight coupling of both registries is a good idea. There are similarities but this is only a little more than convenience-design and not needed at all.

What do you think?

**Comment by raszuk** [comment]
It is hard to tell who says what ... when you paste Alvaro's comment it looks like this is your comment then you are commenting on it :) 

I have a mixed feelings about what's the right thing to do here.  Fact is that many fields are the same so types should also be the same for consistency across v4 & v6. If we have different registries types will mismatch most likely. 

I would a little bit lean your way to keep the registries separate. (This is already done that way for other flow spec extensions like L2 etc ...)

**Comment by suehares** [comment]
Chris: 
I recommend you do want Alvaro stated here.  List both values for both this document and RFC5575bis. 

The issue is one of practical use.   Make it easy for people to find the information.  Linking the registries is ok.  
The IANA folks are good at sorting out problems with the registries. 

Do you need me to suggest text?

**Comment by stoffi92** [comment]
@suehares: If you can suggest a format of the registry I can edit the document. However, when I started editing the table I noticed that the type names in ipv4 do not match those in ipv6:

Can we have a table in the registry that looks like this?

```
+=======+=========================+======+======+===============================+
| Value | Name                    | IPv4 | IPv6 | Reference                     |
+=======+=========================+======+======+===============================+
| 1     | Destination Prefix      |  Y   |      | [RFC-ietf-idr-rfc5575bis-26]  |
|       | Destination IPv6 Prefix |      |  Y   | [this document]               |
+-------+-------------------------+------+------+-------------------------------+
| 2     | Source Prefix           |  Y   |      | [RFC-ietf-idr-rfc5575bis-26]  |
|       | Source IPv6 Prefix      |      |  Y   | [this document]               |
+-------+-------------------------+------+------+-------------------------------+
| 3     | IP Protocol             |  Y   |      | [RFC-ietf-idr-rfc5575bis-26]  |
|       | Next Header             |      |  Y   | [this document]               |
+-------+-------------------------+------+------+-------------------------------+
| 4     | Port                    |  Y   |  Y   | [RFC-ietf-idr-rfc5575bis-26]  |
+-------+-------------------------+------+------+-------------------------------+
....
+-------+-------------------------+------+------+-------------------------------+
| 13    | Flow Label              |      |  Y   | [this document]               | 
+-------+-------------------------+------+------+-------------------------------+
```

**Comment by stoffi92** [comment]
//doc 
Changed IANA considerations to merge IPv4/IPv6 FS types into one registry.

**Comment by suehares** [comment]
The table looks fine to me.
