### ISSUE TITLE
IESG Barry Leiba - Review

### ISSUE THREAD

**Issue by stoffi92** [stoffi92/draft-ietf-idr-flow-spec-v6#57]
Barry Leiba writes:
----------------------------------------------------------------------
DISCUSS:
----------------------------------------------------------------------

This should be extremely straightforward: either there’s a typo... or I simply
don’t understand.  In the Abstract:

  Dissemination of Flow Specification Rules provides a Border Gateway
  Protocol extension for the propagation of traffic flow information
  for the purpose of rate limiting or filtering IPv4 protocol data
  packets.

Is that supposed to say “IPv6”?

----------------------------------------------------------------------
COMMENT:
----------------------------------------------------------------------

A few minor comments:

— Section 3.1 —

  The offset has been defined
  to allow for flexible matching on part of the IPv6 address where it
  is required to skip (don't care) of N first bits of the address.

I can’t parse this sentence, nor make sense of the parenthetical.  Can you
reword it?

  In the case Length minus Offset is 0 every address matches.  Length
  MUST always be in the range 0-128 and Length minus Offset MUST always
  be 0 or more, otherwise this component is malformed.

Is there actually value in allowing 129 ways to match every address
(length=offset=0, length=offset=1, length=offset=87, and so on)?  If not, it
seems less prone to error to say that length=offset=0 matches every address,
and otherwise length MUST be greater than offset or the component is malformed.
No?

— Section 3.8.1 —

  Neither for the destination prefix pattern (length - offset = 32 bit)
  nor for the source prefix pattern (length - offset = 40 bit) any
  padding is needed (both patterns end on a octet boundary).

This isn’t grammatical.  How about this?:

NEW
  Padding is not needed either for the destination prefix pattern
  (length - offset = 32 bit) or for the source prefix pattern
  (length - offset = 40 bit), as both patterns end on a octet
  boundary.
END

**Comment by stoffi92** [comment]
Susan writes:

It's an editorial error rather than a simple typo.   We edited the original abstract to provide a shorter text after comments from Alvaro, and it is now confusing.   
-----------
Old/
  Dissemination of Flow Specification Rules provides a Border Gateway
  Protocol extension for the propagation of traffic flow information
  for the purpose of rate limiting or filtering IPv4 protocol data
  packets.   

   This document extends I-D.ietf-idr-rfc5575bis with IPv6
  functionality.  It also updates I-D.ietf-idr-rfc5575bis by changing
  the IANA Flow Spec Component Types registry.
/
New/
  The Dissemination of Flow Specification Rules [I-D.ietf-idr-rfc5575bis] 
  provides an Border Gateway Protocol extension for the propagation of traffic flow information
  for the purpose of rate limiting or filtering IPv4 protocol data
  packets. 

  This document extends I-D.ietf-idr-rfc5575bis with IPv6
  functionality.  It also updates I-D.ietf-idr-rfc5575bis by changing
  the IANA Flow Spec Component Types registry.
/ 

Thanks for catching this error early.   We'll quickly change that error. 

The remainder of the errors are commented below. 

Thank you for your early comments. 

Sue

**Comment by stoffi92** [comment]
> Is there actually value in allowing 129 ways to match every address (length=offset=0, length=offset=1, length=offset=87, and so on)? If not, it seems less prone to error to say that length=offset=0 matches every address, and otherwise length MUST be greater than offset or the component is malformed.
> No?
> [Sue: The flexibility seemed to be important to the operators. We can recheck with the
> WG if you wish.]

I do not think that the WG ever discussed this. For clarity I would prefer to go for Barry's suggested change.

Christoph

**Comment by suehares** [comment]
Christoph - I agree that you should push Barry's comment next.   We'll have the WG review the final text after the IESG has finished editing.

**Comment by stoffi92** [comment]
all edited into the document
